### ISSUE TITLE
py4j related error?

### ISSUE THREAD

**Issue by shovsj** [brightics/studio#109]
미처 캡쳐는 못했는데, key-value store? 관련 에러가 한번 난 후 다음과 같은 에러가 계속 나는 것 같아요.
재현은 어떻게 하는지 모르겠네요. 까먹을까봐 남겨둡니다.

![image](https://user-images.githubusercontent.com/37683852/50088952-cdc9d180-0247-11e9-9540-1d6e73586a57.png)

JOB ID: c_8Gld9aJmsVeRRFrG_201812172203049420
java.lang.Throwable: Traceback (most recent call last):
  File "C:\Users\SDS\Desktop\brightics-studio\brightics-studio\brightics-server\functions\python\brightics\brightics_python_runner.py", line 107, in _executer
    exec(exec_code_object, self._globals)
  File "<string>", line 4, in <module>
  File "C:\Users\SDS\Desktop\brightics-studio\brightics-studio\brightics-server\functions\python\brightics\brightics_data_api.py", line 156, in put_data
    gateway.notify_data_updated(key, status)
  File "C:\Users\SDS\Desktop\brightics-studio\brightics-studio\brightics-server\functions\python\brightics\brightics_java_gateway.py", line 107, in notify_data_updated
    self._gateway.entry_point.notifyDataUpdated(key, status)
  File "C:\Users\SDS\Desktop\brightics-studio\brightics-studio\lib\python\Lib\site-packages\py4j\java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "C:\Users\SDS\Desktop\brightics-studio\brightics-studio\lib\python\Lib\site-packages\py4j\protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling t.notifyDataUpdated.
: com.samsung.sds.brightics.common.core.exception.BrighticsCoreException: This thread user does not exist.
	at com.samsung.sds.brightics.agent.util.ThreadUtil.getCurrentUser(ThreadUtil.java:12)
	at com.samsung.sds.brightics.agent.context.ContextManager.getCurrentUserContextSession(ContextManager.java:97)
	at com.samsung.sds.brightics.agent.context.ContextManager.updateCurrentDataStatus(ContextManager.java:119)
	at com.samsung.sds.brightics.agent.context.python.PythonContext.notifyDataUpdated(PythonContext.java:477)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
	at com.samsung.sds.brightics.agent.context.python.PythonContext.run(PythonContext.java:375)
	at com.samsung.sds.brightics.agent.context.python.PythonContext.run(PythonContext.java:335)
	at com.samsung.sds.brightics.agent.context.python.PythonContext.runScript(PythonContext.java:111)
	at com.samsung.sds.brightics.agent.service.TaskService.executeScript(TaskService.java:178)
	at com.samsung.sds.brightics.agent.service.TaskService.executeTaskToContext(TaskService.java:146)
	at com.samsung.sds.brightics.agent.service.TaskService.getTaskResult(TaskService.java:98)
	at com.samsung.sds.brightics.agent.service.TaskService$1.run(TaskService.java:66)

**Comment by shovsj** [comment]
java heap memory가 한번 터진 것 같네요.
