### ISSUE TITLE
regression - auto random forest train for regression exception

### ISSUE THREAD

**Issue by IreneSSS** [brightics/studio#286]
JOB ID: c_bmc05PYDOVt9k1yl_201901271057155680
org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:205)
	at org.apache.spark.ml.tuning.CrossValidator$$anonfun$4$$anonfun$6.apply(CrossValidator.scala:164)
	at org.apache.spark.ml.tuning.CrossValidator$$anonfun$4$$anonfun$6.apply(CrossValidator.scala:164)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at org.apache.spark.ml.tuning.CrossValidator$$anonfun$4.apply(CrossValidator.scala:164)
	at org.apache.spark.ml.tuning.CrossValidator$$anonfun$4.apply(CrossValidator.scala:144)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at org.apache.spark.ml.tuning.CrossValidator.fit(CrossValidator.scala:144)
	at com.samsung.sds.lab.brightics.function.AutoRandomForestTrainForRegression.core(AutoRandomForestTrainForRegression.scala:328)
	at com.samsung.sds.lab.brightics.function.AutoRandomForestTrainForRegression.process(AutoRandomForestTrainForRegression.scala:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.samsung.sds.brightics.common.function.runner.LegacyFunctionRunner$.runFunction(LegacyFunctionRunner.scala:277)
	at com.samsung.sds.brightics.common.function.runner.LegacyFunctionRunner$.function(LegacyFunctionRunner.scala:48)
	at $ujeshimsamsungcom$line19.$ujeshimsamsungcom$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:36)
	at $ujeshimsamsungcom$line19.$ujeshimsamsungcom$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:48)
	at $ujeshimsamsungcom$line19.$ujeshimsamsungcom$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:50)
	at $ujeshimsamsungcom$line19.$ujeshimsamsungcom$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:52)
	at $ujeshimsamsungcom$line19.$ujeshimsamsungcom$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:54)
	at $ujeshimsamsungcom$line19.$ujeshimsamsungcom$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:56)
	at $ujeshimsamsungcom$line19.$ujeshimsamsungcom$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:58)
	at $ujeshimsamsungcom$line19.$ujeshimsamsungcom$read$$iw$$iw$$iw$$iw$$iw.<init>(<console>:60)
	at $ujeshimsamsungcom$line19.$ujeshimsamsungcom$read$$iw$$iw$$iw$$iw.<init>(<console>:62)
	at $ujeshimsamsungcom$line19.$ujeshimsamsungcom$read$$iw$$iw$$iw.<init>(<console>:64)
	at $ujeshimsamsungcom$line19.$ujeshimsamsungcom$read$$iw$$iw.<init>(<console>:66)
	at $ujeshimsamsungcom$line19.$ujeshimsamsungcom$read$$iw.<init>(<console>:68)
	at $ujeshimsamsungcom$line19.$ujeshimsamsungcom$read.<init>(<console>:70)
	at $ujeshimsamsungcom$line19.$ujeshimsamsungcom$read$.<init>(<console>:74)
	at $ujeshimsamsungcom$line19.$ujeshimsamsungcom$read$.<clinit>(<console>)
	at $ujeshimsamsungcom$line19.$ujeshimsamsungcom$eval$.$ujeshimsamsungcom$result$lzycompute(<console>:5)
	at $ujeshimsamsungcom$line19.$ujeshimsamsungcom$eval$.$ujeshimsamsungcom$result(<console>:5)
	at $ujeshimsamsungcom$line19.$ujeshimsamsungcom$eval.$ujeshimsamsungcom$result(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:786)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.callEither(IMain.scala:790)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.evalEither(IMain.scala:805)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.eval(IMain.scala:624)
	at scala.tools.nsc.interpreter.IMain.eval(IMain.scala:1074)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at com.samsung.sds.brightics.agent.context.scala.ScalaContext.run(ScalaContext.java:230)
	at com.samsung.sds.brightics.agent.context.scala.ScalaContext.run(ScalaContext.java:214)
	at com.samsung.sds.brightics.agent.context.scala.ScalaContext.runFunction(ScalaContext.java:123)
	at com.samsung.sds.brightics.agent.service.TaskService.executeFunction(TaskService.java:165)
	at com.samsung.sds.brightics.agent.service.TaskService.executeTaskToContext(TaskService.java:158)
	at com.samsung.sds.brightics.agent.service.TaskService.getTaskResult(TaskService.java:100)
	at com.samsung.sds.brightics.agent.service.TaskService$1.run(TaskService.java:68)
Caused by: java.lang.IllegalArgumentException: requirement failed: DecisionTree requires maxBins (= 15) to be at least as large as the number of values in each categorical feature, but categorical feature 3 has 24 values. Considering remove this and other categorical features with a large number of values, or add more training examples.
	at scala.Predef$.require(Predef.scala:224)
	at org.apache.spark.ml.tree.impl.DecisionTreeMetadata$.buildMetadata(DecisionTreeMetadata.scala:137)
	at org.apache.spark.ml.tree.impl.RandomForest$.run(RandomForest.scala:105)
	at org.apache.spark.ml.regression.RandomForestRegressor.train(RandomForestRegressor.scala:130)
	at org.apache.spark.ml.regression.RandomForestRegressor.train(RandomForestRegressor.scala:45)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:82)
	at org.apache.spark.ml.Estimator.fit(Estimator.scala:61)
	at org.apache.spark.ml.tuning.CrossValidator$$anonfun$4$$anonfun$5$$anonfun$apply$1.apply$mcD$sp(CrossValidator.scala:152)
	at org.apache.spark.ml.tuning.CrossValidator$$anonfun$4$$anonfun$5$$anonfun$apply$1.apply(CrossValidator.scala:151)
	at org.apache.spark.ml.tuning.CrossValidator$$anonfun$4$$anonfun$5$$anonfun$apply$1.apply(CrossValidator.scala:151)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at org.spark_project.guava.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$1.execute(ExecutionContextImpl.scala:136)
	at scala.concurrent.impl.Future$.apply(Future.scala:31)
	at scala.concurrent.Future$.apply(Future.scala:494)
	at org.apache.spark.ml.tuning.CrossValidator$$anonfun$4$$anonfun$5.apply(CrossValidator.scala:160)
	at org.apache.spark.ml.tuning.CrossValidator$$anonfun$4$$anonfun$5.apply(CrossValidator.scala:150)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at org.apache.spark.ml.tuning.CrossValidator$$anonfun$4.apply(CrossValidator.scala:150)
	... 51 more

**Comment by jisujeong** [comment]
'Auto Random Forest' is in Enterprise version only.
This github is for Studio version.
Please send me an e-mail. (jjisu.jeong@samsung.com)
It will be nice if you attach your data and parameter information.
