### ISSUE TITLE
studio launcher 실행 후 python Process 사용 간 에러

### ISSUE THREAD

**Issue by jenyo0** [brightics/studio#598]
로컬 업로드 파일 선택 후 upload 프로세스 실행 간 아래와 같은 에러가 발생하고 있습니다. 
파이썬 프로세스 사용하려고 하면 런처에서 잠깐 프로세스가 떳다가 꺼지는 것 같습니다. 

16:04:01.545 ERROR [] Failed to start external python process - MDC:[] CLASS:[PythonProcessManager]
16:04:01.551 ERROR [] Task(645e3996) by brightics@samsung.com is failed.  - MDC:[] CLASS:[TaskService]
com.samsung.sds.brightics.common.core.exception.BrighticsCoreException: Cannot execute python process. Failed to start external python process.
	at com.samsung.sds.brightics.agent.context.python.PythonProcessManager.startPythonProcess(PythonProcessManager.java:205)
	at com.samsung.sds.brightics.agent.context.python.PythonProcessManager.init(PythonProcessManager.java:88)
	at com.samsung.sds.brightics.agent.context.python.PythonContext.init(PythonContext.java:53)
	at com.samsung.sds.brightics.agent.context.ContextManager.getRunnerAsContext(ContextManager.java:100)
	at com.samsung.sds.brightics.agent.service.TaskService.executeFunction(TaskService.java:203)
	at com.samsung.sds.brightics.agent.service.TaskService.executeTaskToContext(TaskService.java:165)
	at com.samsung.sds.brightics.agent.service.TaskService.getTaskResult(TaskService.java:115)
	at com.samsung.sds.brightics.agent.service.TaskService$1.run(TaskService.java:83)
16:04:01.598 INFO  [] 645e3996-main - MDC:[] CLASS:[TaskReceiver]
16:04:01.599 INFO  [] Finished task ID : 645e3996 - MDC:[] CLASS:[TaskReceiver]
16:04:01.612 INFO  [] Task(645e3996) by brightics@samsung.com is finished. - MDC:[] CLASS:[TaskService$1]
16:04:01.626 ERROR [c_qj0zQPIhxkhpcYRa_201907101603279580]         [TASK ERROR] Cannot execute python process. Failed to start external python process. - MDC:[fid=f55ar7gkutpaha63, mid=mhd7dag3pyeww3dg, jid=c_qj0zQPIhxkhpcYRa_201907101603279580, indent=        , user=brightics@samsung.com, taskId=645e3996] CLASS:[FunctionWork]
16:04:01.627 ERROR [c_qj0zQPIhxkhpcYRa_201907101603279580]       [FUNCTION ERROR] [Load] - MDC:[fid=f55ar7gkutpaha63, jid=c_qj0zQPIhxkhpcYRa_201907101603279580, indent=      , mid=mhd7dag3pyeww3dg, user=brightics@samsung.com] CLASS:[FunctionWork]
16:04:01.629 ERROR [c_qj0zQPIhxkhpcYRa_201907101603279580]     [MODEL ERROR] - MDC:[mid=mhd7dag3pyeww3dg, jid=c_qj0zQPIhxkhpcYRa_201907101603279580, indent=    , user=brightics@samsung.com] CLASS:[WorkflowModelRunner]
com.samsung.sds.brightics.common.core.exception.BrighticsUncodedException: Cannot execute python process. Failed to start external python process.
	at com.samsung.sds.brightics.server.common.message.task.TaskMessageManager.messageParser(TaskMessageManager.java:92)
	at com.samsung.sds.brightics.server.common.message.task.TaskMessageManager.getAsyncTaskResult(TaskMessageManager.java:74)
	at com.samsung.sds.brightics.server.common.flowrunner.model.impl.FunctionWork.runTask(FunctionWork.java:108)
	at com.samsung.sds.brightics.server.common.flowrunner.model.impl.FunctionWork.start(FunctionWork.java:81)
	at com.samsung.sds.brightics.common.workflow.context.WorkContext.run(WorkContext.java:48)
	at com.samsung.sds.brightics.common.workflow.model.impl.SequentialWorkflow.start(SequentialWorkflow.java:36)
	at com.samsung.sds.brightics.common.workflow.context.WorkflowContext.run(WorkflowContext.java:55)
	at com.samsung.sds.brightics.common.workflow.model.impl.SequentialWorkflow.start(SequentialWorkflow.java:38)
	at com.samsung.sds.brightics.server.common.flowrunner.model.context.WorkflowContextBuilder$1.start(WorkflowContextBuilder.java:63)
	at com.samsung.sds.brightics.common.workflow.context.WorkflowContext.run(WorkflowContext.java:55)
	at com.samsung.sds.brightics.server.common.flowrunner.WorkflowModelRunner.run(WorkflowModelRunner.java:64)
	at com.samsung.sds.brightics.server.common.flowrunner.JobRunner.run(JobRunner.java:138)
	at com.samsung.sds.brightics.server.common.flowrunner.JobRunner.run(JobRunner.java:115)
	at com.samsung.sds.brightics.server.service.JobService$1.main(JobService.java:98)
	at com.samsung.sds.brightics.server.common.thread.JobModelRunnable.run(JobModelRunnable.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by krazyeom** [comment]
사용하고 있는 OS가 무엇이며, 무엇을 받아서 어떻게 설치를 하신건가요?

**Comment by jenyo0** [comment]
안녕하세요
윈7 64비트 이고 홈페이지를 통해 받았습니다.
현재 전자 기흥사업장에서 근무중인데, 주변에 근무하는 사람들 pc에서는 동일환경에서 문제없이 작동됩니다.
혹시 다른 체크해볼 방법이 있으면 도움을 받고자 합니다.


2019년 7월 11일 (목) 오전 8:50, Sungwook Yeom <notifications@github.com>님이 작성:

**Comment by krazyeom** [comment]
tmp 디렉토리가 아닌곳에 설치하셨죠?

CMD창 실행하고 `설치된곳\brightics-studio\lib\python` 디렉토리로 이동하셔서 python 명령어가 실행되는지 확인 부탁드립니다.

**Comment by krazyeom** [comment]
녹스 '염성욱' 으로 메일 또는 메신져 부탁드립니다.

**Comment by jenyo0** [comment]
안녕하세요.
8월 초까지 자리를 비우게 되어 확인이 바로는 어려울 것 같습니다.
복귀 후 메신저로 문의드리도록 하겠습니다.
감사합니다.

2019년 7월 12일 (금) 오전 9:40, Sungwook Yeom <notifications@github.com>님이 작성:
