### ISSUE TITLE
add function column블럭에 에러가뜹니다

### ISSUE THREAD

**Issue by ekdud7667** [brightics/studio#644]
input table의 column에 price라는 컬럼이 있습니다.
저는 add function column을 이용하여 새로운 result라는 컬럼을 만들고 싶습니다.

-new column name: result
-expression: price
를 넣었는데,
1.  cannot import name '_path'라는 에러가 떴습니다. 왜그런건가요?

2. 새로운 컬럼을 세개정도 더 만들고 싶은데 한 블럭내에서 여러 컬럼을 만들수 있는 방법은 없나요?

3. replace missing  string함수를 이용해서 nan값을 특정 string으로 변경하는것이 아닌, input 테이블의 특정 행,열에 들어있는 데이터로 채울순 없나요?

![image](https://user-images.githubusercontent.com/54248510/63229648-bfe8a800-c23d-11e9-97ec-023c8981969a.png)

`JOB ID: c_187Kd5TQ1xzab197_201908191514068460
java.lang.Exception: ImportError: cannot import name '_path'JOB ID: c_187Kd5TQ1xzab197_201908191514068460
java.lang.Exception: ImportError: cannot import name '_path'
at com.samsung.sds.brightics.agent.context.python.PythonProcessManager.run(PythonProcessManager.java:279)
	at com.samsung.sds.brightics.agent.context.python.PythonProcessManager.run(PythonProcessManager.java:236)at com.samsung.sds.brightics.agent.context.python.PythonContext.runFunction(PythonContext.java:72)
	at com.samsung.sds.brightics.agent.service.TaskService.executeFunction(TaskService.java:203)
	at com.samsung.sds.brightics.agent.service.TaskService.executeTaskToContext(TaskService.java:165)
	at com.samsung.sds.brightics.agent.service.TaskService.getTaskResult(TaskService.java:115)
	at com.samsung.sds.brightics.agent.service.TaskService$1.run(TaskService.java:83)
Caused by: java.lang.Throwable: Traceback (most recent call last):
  File "C:\Users\DaYoung\Desktop\brightics-studio\brightics-server\functions\python\brightics\brightics_python_runner.py", line 125, in _executer
    exec(exec_code_object, self._globals)
  File "<string>", line 4, in <module>
  File "C:\Users\DaYoung\Desktop\brightics-studio\brightics-server\functions\python\brightics\function\extraction\__init__.py", line 25, in <module>
    from .pca import pca
  File "C:\Users\DaYoung\Desktop\brightics-studio\brightics-server\functions\python\brightics\function\extraction\pca.py", line 19, in <module>
    import matplotlib.pyplot as plt
  File "C:\Users\DaYoung\AppData\Roaming\Python\Python37\site-packages\matplotlib\pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "C:\Users\DaYoung\AppData\Roaming\Python\Python37\site-packages\matplotlib\colorbar.py", line 28, in <module>
    import matplotlib.artist as martist
  File "C:\Users\DaYoung\AppData\Roaming\Python\Python37\site-packages\matplotlib\artist.py", line 11, in <module>
    from .path import Path
  File "C:\Users\DaYoung\AppData\Roaming\Python\Python37\site-packages\matplotlib\path.py", line 17, in <module>
    from . import _path, rcParams
ImportError: cannot import name '_path'
	... 7 more`

**Comment by krazyeom** [comment]
1. 뭔가 python path 가 잘못잡힌듯하네요. 혹시 다른 설정 해준게 있나요?
2. Add function Columns 함수를 사용하세요.
3. python script나 Query Executor를 사용하면 됩니다.

**Comment by ekdud7667** [comment]
> 뭔가 python path 가 잘못잡힌듯하네요. 혹시 다른 설정 해준게 있나요?
> Add function Columns 함수를 사용하세요.
> python script나 Query Executor를 사용하면 됩니다.

1. 네 python path폴더> lib폴더> python에 python36._pth에 라이브러리를 추가하기위해

'C:\Users\DaYoung\AppData\Roaming\Python\Python37\site-packages
python36.zip
.

# Uncomment to run site.main() automatically
#import site
Lib
Lib\site-packages
Scripts
C:\Users\SDS\AppData\Local\Temp\
'
맨 윗줄을 추가하였습니다.

**Comment by power4454** [comment]
본인 local(C:\Users\DaYoung\AppData\Roaming\Python\Python37\site-packages\)에 설치된 matplotlib이 잘못된거 같네요. Google에서 검색해보니 다음과 같은 글이 나오네요.

https://stackoverflow.com/questions/49013901/importerror-cannot-import-name-path-matplotlib

matplotlib버전이랑 brightics 버전이 안 맞거나 matplotlib이 설치가 잘못되지 않았나 싶네요.

**Comment by power4454** [comment]
library 추가가 목적이시라면 순서를 바꿔서 본인 로컬폴더를 후순위로 둬서 Brightics 내부 library를 먼저 불러오게 하는게 어떨까요?

**Comment by krazyeom** [comment]
@ekdud7667 Brightics Studio 는 Python 3.6.x 를 지원하고 있으니 참고하세요. 3.7은 지원하지 않습니다.

**Comment by ekdud7667** [comment]
네 감사합니다!
