### ISSUE TITLE
Query Executor 에서 테이블 Join 시 Error 발생

### ISSUE THREAD

**Issue by bomyi** [brightics/studio#648]
Documentation>튜토리얼, Studio1.0
Pre-processing>데이터결합 예제 에서 Query Executor 로 조인 처리 시 아래처럼 오류가 발생하는데 내용분석 부탁드립니다.

Load
06_py_preprocessing_join_english.txt
06_py_preprocessing_join_history.txt

Query Executor 
select *
from  #{DF(0)} a left join #{DF(1)} b
on a.id = b.id

JOB ID: c_kbiOpX8fDpg77hxl_201908201513168440
java.lang.Exception: KeyError: 0

	at com.samsung.sds.brightics.agent.context.python.PythonProcessManager.run(PythonProcessManager.java:263)
	at com.samsung.sds.brightics.agent.context.python.PythonProcessManager.run(PythonProcessManager.java:220)
	at com.samsung.sds.brightics.agent.context.python.PythonContext.runFunction(PythonContext.java:56)
	at com.samsung.sds.brightics.agent.service.TaskService.executeFunction(TaskService.java:187)
	at com.samsung.sds.brightics.agent.service.TaskService.executeTaskToContext(TaskService.java:149)
	at com.samsung.sds.brightics.agent.service.TaskService.getTaskResult(TaskService.java:99)
	at com.samsung.sds.brightics.agent.service.TaskService$1.run(TaskService.java:67)
Caused by: java.lang.Throwable: df_f93728fb
df_00f69bcd
Traceback (most recent call last):
  File "C:\brightics-studio\lib\python\Lib\site-packages\pandas\core\indexes\base.py", line 3078, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\brightics-studio\brightics-server\functions\python\brightics\brightics_python_runner.py", line 109, in _executer
    exec(exec_code_object, self._globals)
  File "<string>", line 8, in <module>
  File "C:\brightics-studio\brightics-server\functions\python\brightics\function\transform\sql\executor.py", line 40, in execute
    res = _get_deserialized_table(sql.read_sql(query, con))
  File "C:\brightics-studio\brightics-server\functions\python\brightics\function\transform\sql\serializer.py", line 30, in _get_deserialized_table
    cols_to_deserialize = _get_serialized_cols(table)
  File "C:\brightics-studio\brightics-server\functions\python\brightics\function\transform\sql\serializer.py", line 16, in _get_serialized_cols
    return [_ for _ in cols if _is_serialized(table[_][0])]
  File "C:\brightics-studio\brightics-server\functions\python\brightics\function\transform\sql\serializer.py", line 16, in <listcomp>
    return [_ for _ in cols if _is_serialized(table[_][0])]
  File "C:\brightics-studio\lib\python\Lib\site-packages\pandas\core\frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "C:\brightics-studio\lib\python\Lib\site-packages\pandas\core\frame.py", line 2700, in _getitem_column
    result = result[key]
  File "C:\brightics-studio\lib\python\Lib\site-packages\pandas\core\frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "C:\brightics-studio\lib\python\Lib\site-packages\pandas\core\frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "C:\brightics-studio\lib\python\Lib\site-packages\pandas\core\generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "C:\brightics-studio\lib\python\Lib\site-packages\pandas\core\internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "C:\brightics-studio\lib\python\Lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0
	... 7 more

**Comment by krazyeom** [comment]
select A.ID as ID, A.English, B.history from #{DF(0)} A LEFT JOIN #{DF(1)} B ON A.ID=B.ID

* 로 하면 동일한 ID값이 중복으로 나와서 keyerror가 발생합니다.  원하는 컬럼을 선택하세요.
